### ISSUE TITLE
Error seen while minting dataset.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#575] opened 2023-04-26 09:11 UTC
Description: /not reproduceable.

Minting error seen while trying to mint github hosted dataset. Upon second mint attempt success was seen.(closing popup and reminting)

https://raw.githubusercontent.com/Itheum/data-assets/main/Misc/Random/Investment%20Categories.xlsx

https://raw.githubusercontent.com/Itheum/data-assets/main/Misc/Random/Investment%20Categories%20Preview.xlsx

![image](https://user-images.githubusercontent.com/121969933/234527732-e7a36728-2468-48c9-ae50-011075be7665.png)

**Comment by damienen** [comment] 2023-04-26 10:43
This is not a bug. It was an error, it can happen sometimes.

Closing for now. If it becomes recurring we will reopen

**Closed by damienen** 2023-04-26 10:43 UTC
