### ISSUE TITLE
Valid URL entered as "Data stream URL" return error upon minting(from contract) indicating that the URL is too long.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#342] opened 2023-03-07 08:25 UTC
Description
Valid URL entered as Data stream URL return error upon minting(from contract) indicating that the URL is too long.
https://www.datarefuge.org/dataset/df571104-2f77-41cd-853f-301e260cc4ad/resource/c3c5b2b5-739c-437f-a1e0-b8bb7e7d4594/download/april_generator2016.xlsx

Steps to generate
1. Mint a dataset with URL "https://www.datarefuge.org/dataset/df571104-2f77-41cd-853f-301e260cc4ad/resource/c3c5b2b5-739c-437f-a1e0-b8bb7e7d4594/download/april_generator2016.xlsx"
2. Fill in remaining feilds.
3. Invoke "Mint and trade as data NFT"

![image](https://user-images.githubusercontent.com/121969933/223365009-70022def-155a-403a-9b87-0eeeacf6e44b.png)

**Comment by damienen** [comment] 2023-03-13 20:10
Duplicate of another issue

**Closed by damienen** 2023-03-13 20:10 UTC
