### ISSUE TITLE
Data NFT Marketplace Listing: Empty listing seen on page load

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#566] opened 2023-04-25 19:58 UTC
Description:

Empty marketplace encountered on page load, despite having items within marketplace listing.

![image](https://user-images.githubusercontent.com/121969933/234388824-0bb8d7fd-ad7f-408a-b0c0-d24128c02bd5.png)

**Comment by icegriffinguru** [comment] 2023-04-26 09:46
Isn't it API issue? @fuzzyduke , @damienen

**Comment by damienen** [comment] 2023-04-26 09:49
It is, but it is not timeout. You can see the problem is "invalid bech32 string length 0"

**Comment by icegriffinguru** [comment] 2023-04-26 10:47
No SC on mainnet.
Closing

**Closed by icegriffinguru** 2023-04-26 10:47 UTC
