### ISSUE TITLE
Ledger issues with viewing Data via Marshal

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#187] opened 2023-01-31 05:42 UTC
Community

testing with Ledger connection. Its also related to "View data" button. This time its letting me sign the tx but after finishing to process, a new web page is loaded in the browser and some errors are shown, also it does not download any data. The web page that pops up usually have one of 2 different errors, depending on the device and browser used. Some times no error appears but also in this case it does not download anything. 
   - On my laptop and smartphone using Chrome browser I got only one error (see firstpicture) 
   - On my smartphone and laptop using Brave browser I got 2 errors
              - the same one as before (see pic no 1) 
              - a totally different error (see pic no 2) 
             
Steps to reproduce
1)Connect with Ledger
2)Mint/Buy 1 Data NFT
3)Click on view Data
4) Receive the error

![image](https://user-images.githubusercontent.com/118804443/215551894-2aeace33-73ad-418d-a562-a4a58c4fafdb.png)
![image](https://user-images.githubusercontent.com/118804443/215551946-7dcbbfba-95dc-4263-82c5-0841cb3d6dd8.png)

_Originally posted by @BogdanCostinas in https://github.com/Itheum/data-dex/issues/150#issuecomment-1409043499_

**Comment by newbreedofgeek** [comment] 2023-02-07 02:39
[Update]

Spent a long time on this today. The issue seems to be that when you sign a message with Ledger, the signature is returned in a "Uint8Array". In the Maiar App (WCV2), the signature is returned as a "string"


E.g.
This is the return for Maiar App. See `signature.buffer`

![image](https://user-images.githubusercontent.com/743169/217131494-e9725458-0b79-429d-b1e6-fe814f92c868.png)

This works perfectly for us, we take this `string value` and then send it to a backend API that can verify the signature using this:
```
const messageObj = new SignableMessage({
      message: Buffer.from(message),
      signature: { hex: () => signatureStrFromAbove }
    });

userVerifier.verify(messageObj);
```

## ERROR  : This is the return for Ledger. See `signature.buffer`:

![image](https://user-images.githubusercontent.com/743169/217132171-33b16d91-fa70-4b9f-a1c0-96afdfbde11c.png)

Unlike Maiar, this is in `Uint8Array` format. I've tried various ways to convert it to a string. Some are detailed [here](https://stackoverflow.com/questions/8936984/uint8array-to-string-in-javascript) and [here](https://ourcodeworld.com/articles/read/164/how-to-convert-an-uint8array-to-string-in-javascript) and [here](https://discourse.mozilla.org/t/efficient-storage-of-arraybuffer-uint8array/59698/3)

But trying these Uint8Array to String conversion usually end up in some malformed string that looks like `Üà¾Ó*LÖÑó_eÅ^ãªç¯}à*ËÊºjÓµ3Ãç|7­!85.´Að«:|'û` OR `'\x169�E�M~\x7FSx�E��I��\x16bM̤�\x01"7\v�\x14�����"\\\b��"wɩ�2��e9)�\x06j�\x0F�v4N����\n'`


## How can we fix this?
It's hard to debug this and work on it in real-time as you need to keep you ledger connected. The easiest way to possibly fix is to create a new UInt8Array locally exactly as what Ledger returned and try some solutions to convert it to a readable string. You can create the exact signature Ledger returned like so:
```
const myMockLedgerSignature = new Uint8Array([22,57,134,69,217,77,126,127,83,120,208,69,175,162,73,201,201,22,98,77,204,164,128,1,34,55,11,173,20,176,143,132,173,205,34,92,8,158,223,34,119,201,169,219,50,244,196,101,57,41,212,6,106,182,15,148,118,52,78,161,185,238,222,10])

```

**Comment by damienen** [comment] 2023-02-07 06:09
```
  const myMockLedgerSignature = new Uint8Array([
    22, 57, 134, 69, 217, 77, 126, 127, 83, 120, 208, 69, 175, 162, 73, 201,
    201, 22, 98, 77, 204, 164, 128, 1, 34, 55, 11, 173, 20, 176, 143, 132, 173,
    205, 34, 92, 8, 158, 223, 34, 119, 201, 169, 219, 50, 244, 196, 101, 57, 41,
    212, 6, 106, 182, 15, 148, 118, 52, 78, 161, 185, 238, 222, 10,
  ]);
  const buffer = Buffer.from(myMockLedgerSignature);
  const hexString = buffer.toString("hex");
  console.log(hexString);
  // logs 16398645d94d7e7f5378d045afa249c9c916624dcca4800122370bad14b08f84adcd225c089edf2277c9a9db32f4c4653929d4066ab60f9476344ea1b9eede0a
  // Result OK
```

Looks good if you do it this way

**Comment by newbreedofgeek** [comment] 2023-02-07 11:24
Will try this:

```
const myMockLedgerSignature = new Uint8Array([
    22, 57, 134, 69, 217, 77, 126, 127, 83, 120, 208, 69, 175, 162, 73, 201,
    201, 22, 98, 77, 204, 164, 128, 1, 34, 55, 11, 173, 20, 176, 143, 132, 173,
    205, 34, 92, 8, 158, 223, 34, 119, 201, 169, 219, 50, 244, 196, 101, 57, 41,
    212, 6, 106, 182, 15, 148, 118, 52, 78, 161, 185, 238, 222, 10,
  ]);
  const buffer = Buffer.from(myMockLedgerSignature);
  const hexString = buffer.toString("hex");
```

**Comment by newbreedofgeek** [comment] 2023-02-21 23:48
@damienen I am a bit time poor this week. I think you understand this issue and can reproduce it right? can you have a look pls

**Comment by damienen** [comment] 2023-02-22 14:01
Just tried. Error not happening anymore. Or at least I can't reproduce it. It works for me.

Note: I am using the MultiversX Ledger App, not the Elrond Ledger App, as Elrond is now deprecated.

I will close this and reopen if needed

**Closed by damienen** 2023-02-22 14:01 UTC
Labels: bug
