### ISSUE TITLE
When on Details Page and connecting wallet, redirect back to the page the user was on

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#826] opened 2023-07-23 08:13 UTC
The Itheum Explorer redirects people to a details page like this:
https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197

The user can then find a best offer and end up in a page like this:
https://stg.datadex.itheum.io/datanfts/marketplace/DATANFTFT4-3ba099-0197/offer-1951

BUT they are not logged in, and now they "Connect their wallet"... 

Current Behaviour:
- After connecting wallet and logging in, the user is redirected to the dashboard and they lose their offer page and they don't buy the Data NFT

Expected Behaviour:
- If a user is on a details page or offer + details page and they connect their wallet, redirect them back to that same page so they can "buy the offer"

**Comment by newbreedofgeek** [comment] 2023-07-23 08:14
FYI @damienen  -- adding this to 1.3 as it's an important UX improvement for our marketplace

**Comment by icegriffinguru** [comment] 2023-07-27 10:53
Fixed

**Comment by damienen** [comment] 2023-07-27 18:15
Whenever I login to your branch (tried locally and on preview link also) I get connected to mainnet EVEN if I select devnet

**Comment by icegriffinguru** [comment] 2023-07-27 18:30
`nativeAuth` attribute was the cause. I've removed it.

**Comment by damienen** [comment] 2023-07-27 18:34
Works now. Closing.

**Closed by damienen** 2023-07-27 18:34 UTC
Labels: enhancement
