### ISSUE TITLE
When I use the copy link button.. i'm getting a "undefined" offer URL param

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#431] opened 2023-03-29 03:51 UTC
Checking copy link here:
<img width="890" alt="image" src="https://user-images.githubusercontent.com/743169/228422155-46cbd111-797f-404c-b36d-c4431be5a56b.png">

is giving me:
https://deploy-preview-429--frosty-hermann-85ca4f.netlify.app/dataNfts/marketplace/DATANFTFT2-71ac28-a7/offer-undefined

**Comment by icegriffinguru** [comment] 2023-03-29 15:37
@newbreedofgeek , can you tell me what you did before the issue happened?
I can't simulate the issue.

**Comment by damienen** [comment] 2023-03-30 06:09
Can't reproduce. Closing

**Closed by damienen** 2023-03-30 06:09 UTC
Labels: bug
