### ISSUE TITLE
Description: Advertise data popup on mobile doesnt give user an option to close popup.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#684] opened 2023-05-26 11:27 UTC
Description
While attempting to mint dataset on mobile, the user cannot close the popup. There is no close option.

![image](https://github.com/Itheum/data-dex/assets/121969933/aa013274-475a-4a74-9234-a52a8a0e06cf)

**Comment by icegriffinguru** [comment] 2023-05-30 06:15
@fuzzyduke , how can i reproduce the case?
I can't find "Not whitelisted" popup on DataNFT minter page

**Comment by damienen** [comment] 2023-05-30 07:31
If you login on mainnet you will see it. You can also change the condition while developing in your local code (invert the IF condition)

**Comment by icegriffinguru** [comment] 2023-06-01 15:07
Fixed

**Comment by fuzzyduke** [comment] 2023-06-01 18:02
@icegriffinguru have tried to log into mainnet on https://deploy-preview-669--frosty-hermann-85ca4f.netlify.app/tradedata
However, the whitelist popup to disallow minting isn't there anymore.

**Comment by icegriffinguru** [comment] 2023-06-01 18:15
@damienen 
@fuzzyduke  can't see "disabled" state.
can you check my fix?

**Comment by icegriffinguru** [comment] 2023-06-01 18:32
@fuzzyduke couldn't see it

**Comment by damienen** [comment] 2023-06-01 19:08
It's vieweable on production, datadex.itheum.io.

Please check the condition for it to be shown, @icegriffinguru . It might be a newly found bug, but a one line fix.

**Comment by icegriffinguru** [comment] 2023-06-01 19:24
"You are not whitelisted" message is shown by this code
`visibility={userData?.contractWhitelistEnabled && !userData.userWhitelistedForMint ? "visible" : "hidden"}`
i have not changed anything related with it.
I checked main branch but have not found any specific issue.

**Comment by icegriffinguru** [comment] 2023-06-01 19:24
SC returns `contractWhitelistEnabled = false` or `userWhitelistedForMint = false`,
the message won't be shown

**Comment by damienen** [comment] 2023-06-01 19:29
SC returns contractWhitelistEnabled = false on mainnet? That's not possible.

On devnet, sure. But on mainnet nope.

**Comment by icegriffinguru** [comment] 2023-06-03 00:17
@damienen 
Found the reason. updateUserData was not called in StoreProvider. 😅 
Whitelist blocking is working on mainnet now.
@fuzzyduke

**Comment by damienen** [comment] 2023-06-03 12:32
Amazing. Good job, @icegriffinguru ! Thank for checking

**Comment by damienen** [comment] 2023-06-04 16:58
Works. Closing.

**Closed by damienen** 2023-06-04 16:58 UTC
