### ISSUE TITLE
All TX actions on the Data NFTs, cause the UI to flicker 2 times

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#337] opened 2023-03-06 02:34 UTC
Current behaviour:
Each time we sign a TX to interact with Data NFTs (buy a SFT, update price on SFT, list an SFT etc), it seem the UI flickers (refreshes) 2 times. 
This probably means that we are capturing some event and reloading/refreshing the page state without checking if TX was "complete"

See video: https://www.loom.com/share/283f4b10644f40ffa3dd5d0bfc715a10

Current behaviour:
ONLy after the TX completes, should the UI refresh to show the updates. e.g. price change etc. The UI should ONLY refresh once.

@damienen assigning all new bugs to you but feel free to delegate to others in team.

**Comment by damienen** [comment] 2023-03-06 21:48
This is expected behavior. The screen is rerendered when the hasPendingTransactions flag is changing.

The values are updated whenever you start a new transaction because you have a pending transaction and it gets reupdated when you finish the transaction. i.e. I believe it's good behavior as the user gets updates for all his actions, whenever tx start, completes, fails, etc.

**Comment by newbreedofgeek** [comment] 2023-03-06 22:31
It’s not good @damienen - it looks glitchy.

the UI should not refresh when hasPendingTX fires - only when the TX has completed and there needs a re-render to show what’s changed

**Comment by damienen** [comment] 2023-03-06 22:40
@newbreedofgeek 

Some updates NEED to happen when the transaction is fired:
1. The user balance has to be updated, because the user actually has less balance than before
2. The buttons have to become disabled, we should not allow the user to send more transactions while one is still pending

But the LoadingSkeleton should not be shown.

**Comment by newbreedofgeek** [comment] 2023-03-07 04:14
yes,  @damienen @icegriffinguru 

ideal behaviour is that "WHEN TX is happening":

1. the action buttons are disabled
2. NO LoadingSkeleton appears (as this makes it look like a glitch)

"AFTER TX is happening":
1. LoadingSkeleton appears to show that TX is done and changes happen (e.g. price changes if user changed offer price)
2. token balances etc update

**Comment by icegriffinguru** [comment] 2023-03-08 09:34
![image](https://user-images.githubusercontent.com/97042732/223676171-576b152f-52e0-435a-a14c-497ad2f7b519.png)

we need to disable all these buttons that can change content or url
@newbreedofgeek , do you think it's fine?

**Comment by damienen** [comment] 2023-03-09 22:41
Yes. That is expected behavior, it's happening on xExchange, too. Let's so it, @icegriffinguru

**Comment by icegriffinguru** [comment] 2023-03-13 11:20
Fixed but needs further check

**Comment by damienen** [comment] 2023-03-13 19:49
Just checked. Some problems:

1. Marketplace buttons both become the bright cyan color (like they are active) instead of staying one active and one inactive.
2. Navbar buttons (trade, wallet, marketplace) change state, but route is not updated. They should not change state either or if it changes state it should also redirect.

We should discuss on a policy on redirects. I'll get back to you.

**Comment by damienen** [comment] 2023-03-14 05:18
> yes, @damienen @icegriffinguru
> 
> ideal behaviour is that "WHEN TX is happening":
> 
> 1. the action buttons are disabled
> 2. NO LoadingSkeleton appears (as this makes it look like a glitch)
> 
> "AFTER TX is complete":
> 
> 1. LoadingSkeleton appears to show that TX is done and state changes happened (e.g. price changes if user changed offer price)
> 2. token balances etc update

The actions button on the data nft tile should be disabled. The other stuff shouldn't necessarily be disabled as stated by Mark.

@icegriffinguru

**Comment by damienen** [comment] 2023-03-14 14:40
The rule of thumb is "don't let the user send other transactions". The other stuff should be available.

i.e I think we can use a hasPendingTransactions as a check for the buttons that send transactions to disable them (check if it is true)

**Comment by icegriffinguru** [comment] 2023-03-14 14:51
> Just checked. Some problems:
> 
> 1. Marketplace buttons both become the bright cyan color (like they are active) instead of staying one active and one inactive.
> 2. Navbar buttons (trade, wallet, marketplace) change state, but route is not updated. They should not change state either or if it changes state it should also redirect.
> 
> We should discuss on a policy on button deactivations. I'll get back to you.

I will resolve the first one.
The second issue is caused because there is no "disable" flag on Link. :((
One possible solution is modifying css. I will try it.

**Comment by icegriffinguru** [comment] 2023-03-14 15:43
> The actions button on the data nft tile should be disabled. The other stuff shouldn't necessarily be disabled as stated by Mark.
> 
> @icegriffinguru

@damienen , which action buttons do you mean?

**Comment by damienen** [comment] 2023-03-14 15:44
Listing, delisting, buying or updating price

**Comment by icegriffinguru** [comment] 2023-03-14 15:46
> Listing, delisting, buying or updating price

All of them become disabled when hasPendingTransactions is true. 🤔

**Comment by damienen** [comment] 2023-03-14 16:11
And all other actions (changing page, etc.) are enabled?

**Comment by damienen** [comment] 2023-03-14 17:07
Can we make them enabled? @icegriffinguru

**Comment by damienen** [comment] 2023-03-14 17:09
Yea. You are right

**Comment by damienen** [comment] 2023-03-14 22:43
Works. Closing

**Closed by damienen** 2023-03-14 22:43 UTC
Labels: bug
