### ISSUE TITLE
Data NFT Marketplace : When buying a Data NFT, the Itheum balance is reset to 0 (and appears after TX is complete)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#830] opened 2023-07-24 10:59 UTC
Setup:
- I had some ITHEUM token balance. e.g. 10 ITHEUM
- I went to the marketplace and bought a Data NFT from someone else

What Happened:
- When the TX was running the ITHEUM token balance on header became 0.00 ITHEUM. Like so:
<img width="1193" alt="image" src="https://github.com/Itheum/data-dex/assets/743169/d7b541c4-9177-4d79-b4c6-1ba1e180c362">
- After the TX was complete, the token balanced fixed it self and no longer showed 0.00 ITHEUM.

What Should happen:
- It should not reset to 0.00 during a TX. The current header token balance should just stay the same as before the TX ran. e.g. 10 ITHEUM
- Once the TX complete, we refresh the token balance like we usually do to show reduced token count

**Comment by icegriffinguru** [comment] 2023-08-03 01:48
@newbreedofgeek , I can't reproduce the issue.
I've checked code in StoreProvider and AppHeader but everything looked fine.
@damienen , Have you ever experienced such issue?

**Comment by damienen** [comment] 2023-08-03 07:29
@fuzzyduke see if you can reproduce it and give steps if possible

**Comment by Enciusan** [comment] 2023-08-11 12:26
I can't reproduce neither.

**Comment by damienen** [comment] 2023-08-14 08:50
Closing then, at least for now

**Closed by damienen** 2023-08-14 08:50 UTC
Labels: bug, frontend
