### ISSUE TITLE
MX Hub login stuck on devnet and seem to loop

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#982] opened 2023-09-06 03:25 UTC
@fuzzyduke raised this on 1.4 after testing yesterday. It's a blocker and @damienen issued a fix via https://github.com/Itheum/data-dex/pull/981#pullrequestreview-1612333715

Which is merged...

We need to test this properly to make sure something else did not break.

@fuzzyduke note that now when you login via XPortal, it wont redirect to "dashboard". which is fine for now... main thing is that it works

**Comment by fuzzyduke** [comment] 2023-09-06 06:53
Tried to run a burn transaction with xportal. Upon signing in xportal, the below was seen. The sign dint seem to be acknowledged by the datadex.

@damienen @newbreedofgeek 

Steps
1. connect to #859 using xportal.
2. Run a burn transaction on an item in the wallet.
3. Sign transaction in the wallet.

It is seen that no continuity is seen on the datadex after signing in the wallet.

Expected behaviour.
1. The transaction should have been processed and the count should have been reduced on the supply.


![Image](https://github.com/Itheum/data-dex/assets/121969933/d4aa0b0a-2e4b-49d9-83ff-76b3133943b2)

**Comment by fuzzyduke** [comment] 2023-09-06 08:31
This was encountered while purchasing via xportal as well.


![Image](https://github.com/Itheum/data-dex/assets/121969933/253eb6fc-3aca-47da-a8a9-5939efcfc555)

**Comment by fuzzyduke** [comment] 2023-09-06 08:47
While attempting a second login to xportal the below is seen. Unsure of the impact of the message in the console.

Was able to scan the QR code and login using Xportal. However for a short period of time noticed the message "Invalid QR code" before it then successfully scanned the QR code and proceeded to successful login.

![Image](https://github.com/Itheum/data-dex/assets/121969933/c30b3650-8447-4d1b-a96a-c3bcc7073e6a)

**Comment by damienen** [comment] 2023-09-06 08:56
It's the xPortal hub login that needs testing, not the xPortal login...

**Comment by fuzzyduke** [comment] 2023-09-06 09:36
Ok, will assume it is not connected in any way, and post these under a new ticket.

Kindly find below the behavior upon clearing cache and cookies.

It seems that the Balance is taken from devnet but shows mainnet.

Also periodically while clearing cookies and cache and reloading the log to that account is still observed, it is not showcased in the loom though.

![Image](https://github.com/Itheum/data-dex/assets/121969933/bcada9df-40e2-4788-b974-10e63118645f)

https://www.loom.com/share/48bc7d2c2a5c4b8fb93136ed9da06a8b?sid=777d3c0f-4a00-4393-88d4-2428d953c9a5

**Comment by damienen** [comment] 2023-09-06 09:47
Just dropped a fix for the mainnet/devnet balance:
https://github.com/Itheum/data-dex/pull/983

**Comment by fuzzyduke** [comment] 2023-09-06 09:48
Odd behaviour seen. Mainnet to devnet redirection observed.

1.Logged into xportal hub on mainnet.
2. Clicked on a data NFT. Seen that it was a 404.
3. Clicked on datadex and it sends me to devnet.

https://www.loom.com/share/7380f7eb162b435689fb4e50cfc4ff24?sid=211fda1d-487a-40c7-9e6d-1478a9114859

**Comment by fuzzyduke** [comment] 2023-09-06 09:54
To add to the loom video.

When using defi wallet the same offer is seen on mainnet

![Image](https://github.com/Itheum/data-dex/assets/121969933/755ac71e-220b-497c-afe1-d255b4c0a981)

But when using xportal hub, it says offer not found 404.

![Image](https://github.com/Itheum/data-dex/assets/121969933/f450b697-fa04-4d0a-95db-a07ab5908293)

**Comment by damienen** [comment] 2023-09-06 10:05
Dropped a fix for this one, too, in the same PR

**Comment by fuzzyduke** [comment] 2023-09-06 12:41
Upon reviewing, fixes commited on hub are reflecting.
Transitions from mainnet to devnet are only seen when redirection is seen on new tab.

Generally for offers redirected to same tab the error of 404 seems to be resolved.

Balance mapping also seems stable at this point. That is, the mainnet is showing mainnet ballance and not devnet balance.

**Closed by fuzzyduke** 2023-09-06 12:41 UTC
Labels: bug
