### ISSUE TITLE
UI Completely breaking when jumping to last page

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#354] opened 2023-03-12 23:26 UTC
Observed behaviour:
- I minted a new Data NFT, when TX was about to complex (but NOT yet complete)
- I clicked on "marketplace"
- I jumped to "last page" via pagination buttons.
- UI crashed and went white. here is the crash view

<img width="799" alt="image" src="https://user-images.githubusercontent.com/743169/224580340-66eb5845-aba3-4fce-9d0b-234e2f9815f5.png">

- I released the page and it was fixed. but the TX UI Toast seems stuck:
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/743169/224580410-b2dc5f70-4bdd-4be3-9cb8-24c0fe2cd528.png">

**Comment by damienen** [comment] 2023-03-13 20:05
Ideally the routing of the marketplace should be made using query params ( /marketplace/market?page=5 ) instead of the current implementation to both avoid that and to use respect good coding practices.

**Comment by icegriffinguru** [comment] 2023-03-14 14:21
> Ideally the routing of the marketplace should be made using query params ( /marketplace/market?page=5 ) instead of the current implementation to both avoid that and to use respect good coding practices.

@damienen , if we set pageIndex as a url param instead of url segment, web wallet redirection will remove url params, won't it?
@Enciusan , why do you think it's a routing problem?
I used dynamic urls.
![image](https://user-images.githubusercontent.com/97042732/225031039-99249173-8c9e-4c5d-bf46-6dde95de5bef.png)

**Comment by icegriffinguru** [comment] 2023-03-14 14:30
> Observed behaviour:
> 
> * I minted a new Data NFT, when TX was about to complex (but NOT yet complete)
> * I clicked on "marketplace"
> * I jumped to "last page" via pagination buttons.
> * UI crashed and went white. here is the crash view
> 
> <img alt="image" width="799" src="https://user-images.githubusercontent.com/743169/224580340-66eb5845-aba3-4fce-9d0b-234e2f9815f5.png">
> 
> * I released the page and it was fixed. but the TX UI Toast seems stuck:
> 
> <img alt="image" width="1345" src="https://user-images.githubusercontent.com/743169/224580410-b2dc5f70-4bdd-4be3-9cb8-24c0fe2cd528.png">

@newbreedofgeek , i think it's because of API query failure and UI got someshow broke. I already added UI exception handling if userData or addressFrozen are not queried.
I will test it more.

**Comment by damienen** [comment] 2023-03-14 14:39
@Enciusan said it's probably a routing problem because of those warnings in the console that are appearing:
"No routes matched location ... "

There is an easy solution to that:
https://github.com/multiversx/mx-sdk-dapp#sending-transactions

You can put a callbackRoute in the sendTransactions call. It defaults to window.location.pathname, but if you dinamically set it to window.location.pathname + queryParams you should be safe, @icegriffinguru

**Comment by icegriffinguru** [comment] 2023-03-14 14:40
Found the cause. There was no check of userData on marketplace (it was in NFT wallet page).
Fixed.

**Comment by damienen** [comment] 2023-03-16 22:01
As I see you can't leave the modal while an NFT is being minted. 

@newbreedofgeek can you share a video or something?

**Comment by damienen** [comment] 2023-03-21 06:28
Unreproducable. Closing

**Closed by damienen** 2023-03-21 06:28 UTC
Labels: bug
