### ISSUE TITLE
Data NFT Marketplace: Claim airdrop doesnt work on Microsoft Edge.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#681] opened 2023-05-26 11:20 UTC
Descriptiion:
Data NFT Marketplace: Claim airdrop doesn't work on Microsoft Edge.

User-OD

**Comment by damienen** [comment] 2023-05-29 06:07
It was a one off thing, API seems to have failed. Can't reproduce. Closing for now

**Closed by damienen** 2023-05-29 06:07 UTC
Labels: bug
