### ISSUE TITLE
Data NFT Minting - Private Beta Testing Bugs and Issues. [🎉 = fixed, 👍 = looking into, 👀 = suggestion/not high priority but will be looked into]

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#150] opened 2022-12-28 14:05 UTC
- [x] In the trade data form, manually select the royalty box and clear it. NaN appears. Ideal scenario is that user can manually enter a number without NaN appearing.. if this is too hard, then the user cannot clear this field manually and only can click on the top/down arrows to select values.
<img width="147" alt="image" src="https://user-images.githubusercontent.com/743169/209823556-62d8a504-af15-4dbc-a2ea-ff18a71e5b87.png">

Same thing happens with Number of Copies:
<img width="172" alt="image" src="https://user-images.githubusercontent.com/743169/211275498-e7881ba5-96b7-4122-ba50-fe2c6b7d0e1e.png">

**Comment by newbreedofgeek** [comment] 2023-01-06 17:58
- [ ] When the Trade Data Form opens, along with checking for values from smart contract for min/max supply/royalty and tax.. also check is the contract is PAUSED. And if so - show a message to user in the same current header error component : "Data NFT Minting is currently paused"

**Comment by newbreedofgeek** [comment] 2023-01-06 17:59
- [ ] When the Trade Data Form opens, along with checking for values from smart contract for min/max supply/royalty and tax.. also check is the contract if current user is  WHITELISTED. And if NOT - show a message to user in the same current header error component with the message : "You are not currently whitelisted to mint Data NFTs". 

Also disable the "Mint & Trade as NFT" button

**Comment by fuzzyduke** [comment] 2023-01-06 19:08
Max Copies is set to 20. Is this the intended max limit? If so, probably the message should be placed as a suggestion but rather as a statement of max quantity.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/121969933/211082186-3602de4d-539f-4f2d-81d5-cbe61079bde3.png">

**Comment by fuzzyduke** [comment] 2023-01-06 19:10
UI Suggestion:
Clear visual segregation suggested between short title, title and description. 
![image](https://user-images.githubusercontent.com/121969933/211082376-e8d53b64-1e84-47ea-833f-e447545128eb.png)

**Comment by fuzzyduke** [comment] 2023-01-06 19:15
Cosmetic:

"Read Terms of Use" and "Read about Anti-Spam Fee" popups need to be updated with content.

<img width="641" alt="image" src="https://user-images.githubusercontent.com/121969933/211083210-d4c99813-0f32-4f17-a17e-6cd04ffca152.png">

**Comment by fuzzyduke** [comment] 2023-01-06 19:31
Wallet: Maiar defi wallet

Description:
Cancelling a transaction from wallet during Data NFT minting process takes user back to the popup however exiting the popup should be more user friendly. Currently the user has to click close on the error message to close the popup "Data Advertising Progress"

This action also closes the main popup "Trade a Data Stream as a Data NFT-FT" and clears the data entered.

Steps
1. Add in details to mint the Data NFT - https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/selldata
2. Click "Mint and Trade as NFT"

Expected Result
1. Once the Transaction is cancelled it should be easier to get to the "Trade a Data Stream as a Data NFT-FT" page.
2. The data entered should be retained on page "Trade a Data Stream as a Data NFT-FT" even if the transaction is cancelled.

Actual Result
1. Once the transaction is cancelled an error message is seen. Upon closing this message the navigation is seen to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/selldata

Images
Page - Trade a Data Stream as a Data NFT-FT
<img width="640" alt="image" src="https://user-images.githubusercontent.com/121969933/211085675-bf4495b1-4be0-4313-be9e-3a8f597c12fd.png">

Page - Data Advertising Progress
![image](https://user-images.githubusercontent.com/121969933/211083534-046f8599-35d8-4b37-8a01-cbe3f9dcefcc.png)

**Comment by fuzzyduke** [comment] 2023-01-06 19:46
Cosmetic:

Popup probably needs a timeout until it closes. Currently stays until specifically closed.

![image](https://user-images.githubusercontent.com/121969933/211087863-2d276af1-951e-46c2-938c-6c8f66210417.png)

**Comment by newbreedofgeek** [comment] 2023-01-09 09:15
> Wallet: Maiar defi wallet
> 
> Description: Cancelling a transaction from wallet during Data NFT minting process takes user back to the popup however exiting the popup should be more user friendly. Currently the user has to click close on the error message to close the popup "Data Advertising Progress"
> 
> This action also closes the main popup "Trade a Data Stream as a Data NFT-FT" and clears the data entered.
> 
> Steps
> 
> 1. Add in details to mint the Data NFT - https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/selldata
> 2. Click "Mint and Trade as NFT"
> 3. Cancel wallet transaction when prompted.
> 
> Expected Result
> 
> 1. Once the Transaction is cancelled it should be easier to get to the "Trade a Data Stream as a Data NFT-FT" page.
> 2. The data entered should be retained on page "Trade a Data Stream as a Data NFT-FT" even if the transaction is cancelled.
> 
> Actual Result
> 
> 1. Once the transaction is cancelled an error message is seen. Upon closing this message the navigation is seen to https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/selldata
> 
> Images Page - Trade a Data Stream as a Data NFT-FT <img alt="image" width="640" src="https://user-images.githubusercontent.com/121969933/211085675-bf4495b1-4be0-4313-be9e-3a8f597c12fd.png">
> 
> Page - Data Advertising Progress ![image](https://user-images.githubusercontent.com/121969933/211083534-046f8599-35d8-4b37-8a01-cbe3f9dcefcc.png)

- [ ] Update the UI so that when user closes the "process error" box, then the screen should not "hard reset" but the progress popup closes and the form is still on screen with user filled out data

**Comment by newbreedofgeek** [comment] 2023-01-09 09:34
- [ ] Web Wallet: After user mints it redirects to web wallet and comes back with "Data NFT Minting" toast showing but the progress model closed. It's fine if the progress model closes, but once the "Data NFT Minting" is a success, we need to show a Chakra Popup with the same message as we do for other wallet progress updates, e.g.:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/743169/211277940-bfd0edc6-fbb7-431a-a459-d331a674ec64.png">

<img width="476" alt="image" src="https://user-images.githubusercontent.com/743169/211277055-0a104e6b-c609-4941-b3cf-28b40cf8afeb.png">

**Comment by newbreedofgeek** [comment] 2023-01-10 04:43
- [ ] If the user mints an NFT and then immediately tries to mint again, they get the below error. A better UX would be to show a UI timer or message with "You need to wait XX until you can mint again". This timeout can be fetched from the Smart Contract.

<img width="947" alt="image" src="https://user-images.githubusercontent.com/743169/211463717-544461ef-a23a-49a7-89e0-faba438dc9d8.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/743169/211463688-d5ffca0d-3c93-4568-a943-188a004185f3.png">

**Comment by newbreedofgeek** [comment] 2023-01-10 06:00
- [ ] "Frozen" UI design has not been implemented, based on new smart contract deployed today - we can query the contract for user data and get list of frozen SFTs. So this UI can not be built

<img width="284" alt="image" src="https://user-images.githubusercontent.com/743169/211473106-99334712-d406-4009-bf09-a2c26b42e1be.png">

**Comment by newbreedofgeek** [comment] 2023-01-10 10:13
- [ ] When Min Royalties are more than 0, it should update the input box correctly. Here we have Min Royalties 10% but text box is showing 0

<img width="156" alt="image" src="https://user-images.githubusercontent.com/743169/211523360-3a65eece-7e19-421e-8656-9145cda0ef0d.png">

**Comment by newbreedofgeek** [comment] 2023-01-10 10:29
- [ ] Error handling if NFT.strong fails. Currently if the IPFS save step fails, it just gets stuck in below screen. We need some error handling to tell user there was an issue. 

<img width="987" alt="image" src="https://user-images.githubusercontent.com/743169/211526805-d4c6499c-4c7d-497c-a04a-4583ef9206e9.png">

We need to show this error box with the message, "IPFS storage has failed; no gas was deducted. Please try again".

<img width="469" alt="image" src="https://user-images.githubusercontent.com/743169/211527036-6ff76a83-cbd4-4433-8bc9-e7193ecca65f.png">

**Comment by icegriffinguru** [comment] 2023-01-10 13:01
> Max Copies is set to 20. Is this the intended max limit? If so, probably the message should not be placed as a suggestion but rather as a statement of max quantity.
> 
> <img alt="image" width="279" src="https://user-images.githubusercontent.com/121969933/211082186-3602de4d-539f-4f2d-81d5-cbe61079bde3.png">

it's `maxSupply` value
(`Suggested: less than {maxSupply}</Text>`)

**Comment by BogdanCostinas** [comment] 2023-01-10 18:03
Visual  Issue/Bug/Feedback

Wallet: Maiar App 
Browser: Google Chrome 
Device: Laptop 

Description: Minting a Data NFT and owning one is really good, but what happen when I want to burn some of this supply? I can see how many Data NFTs are in the "collection" how many are out there, and I can Burn. The burn function worked properly ; but when checking after a refresh my supply is 4 out of 5. 

Suggestion: After burning- Update the maximum number of NFTs from that collection 
If not possible- A "warning" message that x NFTs were burned



Steps

1) Go to : https://deploy-preview-124--frosty-hermann-85ca4f.netlify.app/
2) Mint a Data NFT with more than 1 as the total supply
3) Go and see your Data NFT
4) Burn some of this supply ( min 1 ) 
5 ) Check the description of the Data NFT


Expected Result

After burning I expected that the total supply to decrease with the amount of burned NFTs ( Visual ) 


Actual Result

The Maximum supply remained as minted 



![image](https://user-images.githubusercontent.com/118804443/211625633-ad6a4fe3-b23d-4f32-91f6-9f5920bbf2e3.png)

**Comment by BogdanCostinas** [comment] 2023-01-10 19:31
Small Suggestion
Currently, there is a " You must agree on terms of use "
Maybe we can change that text to " You must READ and Agree on Terms of Use
![image](https://user-images.githubusercontent.com/118804443/211644058-2dacbb81-39ad-4341-880d-b285f88fd0aa.png)

**Comment by BogdanCostinas** [comment] 2023-01-10 19:54
Wallet: Maiar App
Browser: Google Chrome
Device: Laptop

Description: During the minting process your wallet is disconnected, and somehow the UI keeps you logged in. The pop up message presented in the picture attached it's still there and it's annoying that you need to refresh the page in order to make it disappear. Maybe adding a "close" button on that pop-up message?


Steps

1) Go to Itheum Data DEX 
2) "Play around" or wait long enough until your wallet it's disconnected from the Data DEX
3) Go and Advertise your Data
4) Add the cloud storage links, title, description, how many NFTs and the royalties; Accept the terms of use
5) Click on Mint
6) Once the pop-up gives you the notification that you have a transaction to sign in to your wallet, this screen is "stuck" with this action and you need to refresh 

Expected Behaviour
Once my wallet has  been disconnected from Itheum Data DEX I expect to be logged out or if I am in the minting process to have a way to close that and click on disconnect myself

Actual Behavior:

I am kept logged in with no possibility of closing that pop-up message

![image](https://user-images.githubusercontent.com/118804443/211647603-d5e9724a-01a8-46a6-b6e5-032848ba2313.png)

**Comment by BogdanCostinas** [comment] 2023-01-12 09:03
UI Suggestion:

Description: Data NFT Wallet shows the NFTs in a quite big format. 
Suggestion: *Shrink the Data NFT Image
                    *Keep in the "preview" only what's in a green area and add an "EXPAND" button to show all the details of the NFT, such as " Owner, copies, description, creator etc "


![image](https://user-images.githubusercontent.com/118804443/212023188-366912c0-9804-4847-8680-245cceb6a4ab.png)

**Comment by newbreedofgeek** [comment] 2023-01-13 09:52
- [ ] Select these input boxes and hit the down and up keyboard arrow and the values go past the min and max values. These boxes should NOT go past the min/max values

<img width="395" alt="image" src="https://user-images.githubusercontent.com/743169/212290679-b0e710ca-9f1c-42cc-adca-c16b04450ff7.png">

**Comment by newbreedofgeek** [comment] 2023-01-13 11:06
- [ ] Here the input box needs to start at 10 (as minRoyalty is 10) and the Min and Max values on the input box SHOULD NOT go over or under this if user interacts with it (via the arrows or up/down keys). Do the same with the Supply box as well

<img width="241" alt="image" src="https://user-images.githubusercontent.com/743169/212305524-b5f895bb-444d-4bd5-bf1a-6626aef4968d.png">

<img width="442" alt="image" src="https://user-images.githubusercontent.com/743169/212305779-56d84ffd-3112-4a2e-8d74-0b51a21fdeea.png">


@icegriffinguru

**Comment by fuzzyduke** [comment] 2023-01-17 17:57
Suggestion:

Feature: Tagging

1. There should be tags associated to Data NFT for the purpose of filtering, this can be iterated upon. 
     a. primary tags/filter; File Type[json, doc, xls, image, video], Industry[health, retail, gaming]
     b. additional tags; tutorial, analytics, rawdata, survey, research

**Comment by fuzzyduke** [comment] 2023-01-17 18:01
#Suggestion :

#Feature : Request for dataset with bounty
This is a suggestion that requires refinement.

This feature enables a consumer/buyer to provide a schema of a desired dataset.
The purpose of this feature is to enable the consumer to request for data/research they are in search of, and are willing to buy.

**Comment by fuzzyduke** [comment] 2023-01-17 18:12
![image](https://user-images.githubusercontent.com/121969933/212977864-4f3a072e-a17a-4a46-a943-5062a966b65d.png)
Description
Intended to place in the value '999', However while clicking within box to "Backspace" the value 1, the action is not permitted.

Expected Behaviour
Backspace should be permitted on single digit so the user can input any digit. 

Actual Behaviour
Backspace is not permitted when single digit is within cell.

**Comment by fuzzyduke** [comment] 2023-01-17 18:17
![image](https://user-images.githubusercontent.com/121969933/212978628-853ca873-0750-4678-a785-c1f1763fc7d2.png)
Description:
Attempted to place in the value "44" after selecting the input value "10" to be replaced. The action was not permitted.
This could be because this validation is performed while the user is entering the value instead of performing this validation after leaving the text box.

Expected Behaviour:
A user should be able to select "10" and type in "44" without the validation stopping them from doing so. As this is within acceptable bounds.

**Comment by fuzzyduke** [comment] 2023-01-17 18:26
#Cosmetic suggestion :

Description:

Post minting the data NFT the below popup is seen.
![image](https://user-images.githubusercontent.com/121969933/212980455-bb11a6da-7042-4c37-bac0-51129a69f2bc.png)
Is it practical/feesible to place a link of the Data NFT Wallet within the popup? This be a hyperlink on the term within the popup "Data NFT Wallet"

**Comment by fuzzyduke** [comment] 2023-01-17 18:29
![image](https://user-images.githubusercontent.com/121969933/212981331-02ade829-e378-41f8-977a-6278ab8d52a5.png)
The description of the Data NFT gets truncated. Will we have a detail page for the Data NFT? So all fields can be clearly seen.

**Comment by BogdanCostinas** [comment] 2023-01-17 19:24
Incremental limitaion:

Royalties have an increment set of "5" 
This could be redefined to a 1% when hitting "up or down "
![image](https://user-images.githubusercontent.com/118804443/212993057-6aa74089-1d12-4a1c-9d3e-a1479570c271.png)

**Comment by BogdanCostinas** [comment] 2023-01-17 19:41
We have Claims History

Can we add Data NFT's history?
Minting/Burning/Buying/Selling


![image](https://user-images.githubusercontent.com/118804443/212996154-f3ebc426-3bb4-4e09-94b1-887fcd973291.png)

**Comment by BogdanCostinas** [comment] 2023-01-24 16:53
Community:
Procure your own NFT on the marketplace
The seller of the NFT= Creator of the NFT, the button "Procure" it's available, but the error pop up after you sign the transaction, trying to buy your own NFT

To reproduce :
1) Mint a Data NFT
2) List Your Data NFT
3) Try to procure your own NFT
4---- The results are in the pics attached

Expected Behavior:
1) Either disable the button "Procure" if the seller=creator
2) A warning message that it's your own NFT

![image](https://user-images.githubusercontent.com/118804443/214355216-98d56542-6c41-4574-87f5-ef85b8cc594b.png)
![image](https://user-images.githubusercontent.com/118804443/214356178-5575bd3d-f583-4a1d-a99e-829433297d88.png)

**Comment by BogdanCostinas** [comment] 2023-01-24 18:57
Community:
There is a minor display bug on the Data NFT Marketplace
It's displayed x out of "0"


![image](https://user-images.githubusercontent.com/118804443/214383331-aeefdfa4-81e9-425b-b29a-8583ac6ea57a.png)

**Comment by BogdanCostinas** [comment] 2023-01-24 19:02
Internal
Description:

Pop-up transaction messages have a strange behavior

Browser: Google Chrome
Wallet: Defi Wallet

Steps to reproduce
1) Sign a transaction
2) Sign the second transaction
3) Get the error

Expected behavior:
1)Sign the second transaction and the pop up message to be displayed on top of the first message, not on the front of the first message
2)The TX messages to disappear automatically after some time


![image](https://user-images.githubusercontent.com/118804443/214383636-b26dc064-e382-48b0-b3e6-f60a16ca69f7.png)

**Comment by BogdanCostinas** [comment] 2023-01-24 19:12
Internal: 
Description: "I have read all the terms and agreed with them" box remains checked if you try to procure 1 Data NFT. It's sufficient to click on Procure and check the box and then you can either continue to buy the Data NFT or Cancel, if you try to procure another data NFT the checkbox remains checked in the same webpage session. It resets when you go to another tab ( eg. Home ) 

Steps: 
1) Go to data nft marketplace
2) Try to Procure 1 data nft
3) Click " I have read all the terms and agreed with them"
4) 2 Options ( Procure or Cancel ) have the same output
5) Try to PROCURE another data nft and you already signed that you read the terms and agree with them

Expected behavior:
If I either buy the NFT or close the buying tab, when I open again, or another data NFT, the "I have read all the terms...." it is not "checked" by default

Maiar Chrome Extension
Google Chrome 
Laptop
![image](https://user-images.githubusercontent.com/118804443/214385360-69a0ee0e-35f4-445a-ba17-4406ba235083.png)

**Comment by BogdanCostinas** [comment] 2023-01-24 19:35
Community+Internal:

Suggestion: In the Data NFT Marketplace can we add a button to change the selling price?
Or either delist a small part of the Data NFTs?

**Comment by icegriffinguru** [comment] 2023-01-24 20:43
> Internal: Description: "I have read all the terms and agreed with them" box remains checked if you try to procure 1 Data NFT. It's sufficient to click on Procure and check the box and then you can either continue to buy the Data NFT or Cancel, if you try to procure another data NFT the checkbox remains checked in the same webpage session. It resets when you go to another tab ( eg. Home )
> 
> Steps:
> 
> 1. Go to data nft marketplace
> 2. Try to Procure 1 data nft
> 3. Click " I have read all the terms and agreed with them"
> 4. 2 Options ( Procure or Cancel ) have the same output
> 5. Try to PROCURE another data nft and you already signed that you read the terms and agree with them
> 
> Expected behavior: If I either buy the NFT or close the buying tab, when I open again, or another data NFT, the "I have read all the terms...." it is not "checked" by default
> 
> Maiar Chrome Extension Google Chrome Laptop ![image](https://user-images.githubusercontent.com/118804443/214385360-69a0ee0e-35f4-445a-ba17-4406ba235083.png)

Fixed. Will be reflected at next pull request.

**Comment by BogdanCostinas** [comment] 2023-01-26 19:20
Description : Choosing the exact number as Royalty has a small issue, the 5% increment while typing was solved, and now we can choose 12 17 28 29, etc but there is an issue if I want to manually type 13 I cannot do that, except when I am selecting the second digit. If I am choosing both digits, it returns me the error that cannot be grater than 50 

![image](https://user-images.githubusercontent.com/118804443/214929060-6279057e-7cc6-41ec-93f1-362a82fb3507.png)

**Comment by BogdanCostinas** [comment] 2023-01-26 19:23
Issue Update

"VIEW DATA" using Maiar App ( xPortal ) is "bugged" again 
@damienen @icegriffinguru

**Comment by BogdanCostinas** [comment] 2023-01-26 19:52
Internal Suggestion:


Marketplace--->My Data NFT

We can see which Data NFTs we listed but no other information 
eg. Listing price/ Listing Date
Here also adding a button to change listing price could be usefull
![image](https://user-images.githubusercontent.com/118804443/214935775-4bb480b1-0726-424d-8d08-84f061a6c7ac.png)

**Comment by BogdanCostinas** [comment] 2023-01-27 11:59
Community suggestion:

Filters on the marketplace
I know you already have that in mind 

Internal: Group the Data NFTs listed on Marketplace  based on the Creator/ Owner 
Add a Hyperlink to open a new page for a specific creator/owner on the marketplace 
(Clicking on XYZ's Data NFT to be able to see all the datasets listed by XYZ )

Not urgent, just something that i had in mind

**Comment by BogdanCostinas** [comment] 2023-01-27 12:03
Community suggestion:

The description is limited to 250 characters, can we increase the limit?

**Comment by BogdanCostinas** [comment] 2023-01-27 15:09
Internal Suggestion
Highlighted Tab is usually the active tab, on our Data DEX is other way around

Check the screenshot below
1) active tab
2) inactive tab

Can we highlight the active tab and give a gray nuance to the inactive ones?

![image](https://user-images.githubusercontent.com/118804443/215119338-2d69c89c-d224-45a8-91bf-6a7cf8d7f0f6.png)

**Comment by BogdanCostinas** [comment] 2023-01-27 15:16
Internal:

Description: Try to add some extra characters ( Numbers ) into the price field, and keep doing this until the price reset to 0

Steps to reproduce
Step 1) Mint a data NFT ( if you don't own one ) / Buy one from the Marketplace
Stept 2) Go to Wallet
Step 3) In the "Price" section keep adding numbers ( eg keep on adding 7) 
Step 4 ) Get the bug ( after the e217 the price gets to 0

Expected behavior: Price to be set to maximum Circulating supply/ Total supply

![image](https://user-images.githubusercontent.com/118804443/215120369-2448f8ec-f511-4cdb-ad94-d5cf088c9beb.png)

**Comment by BogdanCostinas** [comment] 2023-01-27 16:52
Internal ( Praveen ) 

Describe the bug
Setting price to 9999 (it seems to permit huge numbers and goes into e+, need to limit the max number here) and 20 results in the attached message after signing the TX.

Expected behavior
Smaller numbers for the price seem to be OK but larger numbers have an error.

Try with 999999 and it will result in a failed tx 

Device used: 
Laptop
Browser Version:
eg: Brave (Latest)
OS: Windows 11 
![image](https://user-images.githubusercontent.com/118804443/215145963-1eee8d1d-9ffd-42f5-933c-e459f00cf6d4.png)

**Comment by BogdanCostinas** [comment] 2023-01-27 20:44
Community:
Description : While Claiming from Claims Portal or Faucet you're not able to see your Data NFTs 

Step 1- Claim from allocation/reward/airdrop
Step 2 - Sign the TX
Step 3 - While waiting for the transaction to be completed, go to Wallet
Step4 - Receive the Error

Expected Behavior: No matter what i am doing, my Data NFT wallet should be visible 


![image](https://user-images.githubusercontent.com/118804443/215190756-8a0dacb8-e6da-43c0-85b7-019190b89057.png)

**Comment by BogdanCostinas** [comment] 2023-01-27 20:50
Community:

Description: While procuring 1 Data NFT, imedtiatlly after signing the TX go to "MY DATA NFTs" and you are able to see all other Data NFT's listed on Marketplace but with one BIG difference. All appear as yours and you can see a " Delist" button, and you can interact with that ( TX fail )

Step1- Go to Data NFT Marketplace
Step2 - Procure 1 Data NFT
Step3 -Quickly swap the pages to "My Data NFT"
Step4 -The visual bug appear

Expected behavior - When i click on the My data nft page after signing the tx to procure 1 Data NFT it's supposed to display my own data NFTs, not the ones listed on marketplace with a delist option
![image](https://user-images.githubusercontent.com/118804443/215194423-ea797beb-296c-4b8f-8097-de8918e33879.png)

**Comment by BogdanCostinas** [comment] 2023-01-29 10:51
Description: Trying to burn more NFTs than the supply and generated multiple error messages, each time you try to set a higher amount it generates another error message

To reproduce
1) Go to Data NFT Wallet
2) Click on Burn
3) Try to burn more NFTs than you actually own
4) Repeat the action 3 multiple times


![image](https://user-images.githubusercontent.com/118804443/213000652-08629c76-50ab-4843-b26c-aa9dfb7b45f1.png)

**Comment by BogdanCostinas** [comment] 2023-01-29 10:54
Suggestion:

Add the "OFFER" button

More context: I'm watching through Data NFTs Marketplace and I see something that I want to procure, but the price might be too spicy, maybe I can offer a lower amount for that particular Data NFT

Add "Bundle" 

Maybe I want to trade 5-6 different datasets but I want to trade them in one pack

**Comment by BogdanCostinas** [comment] 2023-01-29 11:16
Community ( Personally i cannot confirm it, tried with a mobile version with Android, and works ok with my phone, maybe other phones with get this )

Description: After successfully signing a transaction you get a message, that the transaction is going through. If you go to Advertise data and click on the Data Stream URL or another field, everything will be zoomed in and you cannot close the transaction message. On this point zooming out won't work

Step 1) Claim Faucet Tokens
Step 2) Go to Advertise data
Step 3) Click on Data stream URL field 
Step 4 ) Get the error 

Expected behavior:
TX message to be closed automatically or, not to zoom in after clicking on the Data Stream field

See more details in the pics attached:
Pic1 before clicking on Data Stream URL
Pic 2 After clicking on Data Stream URL
![image](https://user-images.githubusercontent.com/118804443/215322403-62b9f7cf-1cc8-4885-a0cb-c83c7c4a21d1.png)
![image](https://user-images.githubusercontent.com/118804443/215322451-23cb8b2f-4187-473a-a2a5-814d85c40aad.png)

**Comment by BogdanCostinas** [comment] 2023-01-29 11:27
Community:

Description: Trying to burn NFTs, if you try to delete the numbers from the keyboard is not working properly, automatically gives you the error that the amount cannot be 0

To reproduce
Step1) Go to your Wallet
Step2 ) selected one Data NFT
Step 3) Click on Burn
Step 4) in the How many do you want to burn area try to delete the preset number 1 and get the error. The same thing applies if you already change to another number, eg 9 and you try to delete

Internal suggestion 
If I try to delete the number written in the box, and it goes to 0, then the burn button is deactivated ( Change it's color too, make it red, until you choose a number higher than 1 and lower than the total supply owned  )

**Comment by BogdanCostinas** [comment] 2023-01-29 11:55
Community observation:

My testing process made me think about the burn option from the perspective of permissions and behavior: so in my tests, I did not mint my own NFT, I bought licenses from the public marketplace and could burn them if I wanted to. To an extreme, I could have purchased all 10 licenses, burnt them all, and made a product that was not minted by me disappear completely. I understand I bought a fully transferable product, but I am not sure I should be able to burn something I did not mint

**Comment by BogdanCostinas** [comment] 2023-01-29 12:37
Community:

Description: Listing an NFT disappears from the wallet, it cannot be found under the Public Marketplace, either under My Data NFT from the Marketplace page

Step1) Buy/Mint 1 data NFT
Step2) List your newly created/procured Data NFT
Step3) Check the Public Marketplace/ My data NFTs and the Data NFTs are not there

Additional context, on the Marketplace there are only 2 Data NFTs on sale 

Expected behavior: Checking on the Data NFT Marketplace or My Data NFT section I expect to be able to see my fresh listed Data NFT
Same behavior using multiple types of wallets/ browsers

**Comment by damienen** [comment] 2023-01-30 15:36
All comments from here have been opened as separate issues. Will close this issue as it's become a doomthread

**Comment by BogdanCostinas** [comment] 2023-01-30 15:43
Internal (Nath )

Description Login with a new wallet ( no XEGLD in the wallet will provide an error- check pic attached )

Steps to reproduce:
Step1) Create a new wallet
Step2) Use the newly created wallet to connect to the Data DEX
Step3) Receive the error

Expected Behavior: I expected this connection to be smooth, with no errors because the wallet was empty.


![image](https://user-images.githubusercontent.com/118804443/215523482-0706a0ae-b6f9-412b-8238-bd305d6c6d7e.png)

**Comment by BogdanCostinas** [comment] 2023-01-30 17:38
Community

testing with Ledger connection. Its also related to "View data" button. This time its letting me sign the tx but after finishing to process, a new web page is loaded in the browser and some errors are shown, also it does not download any data. The web page that pops up usually have one of 2 different errors, depending on the device and browser used. Some times no error appears but also in this case it does not download anything. 
   - On my laptop and smartphone using Chrome browser I got only one error (see firstpicture) 
   - On my smartphone and laptop using Brave browser I got 2 errors
              - the same one as before (see pic no 1) 
              - a totally different error (see pic no 2) 
             
Steps to reproduce
1)Connect with Ledger
2)Mint/Buy 1 Data NFT
3)Click on view Data
4) Receive the error

![image](https://user-images.githubusercontent.com/118804443/215551894-2aeace33-73ad-418d-a562-a4a58c4fafdb.png)
![image](https://user-images.githubusercontent.com/118804443/215551946-7dcbbfba-95dc-4263-82c5-0841cb3d6dd8.png)

**Comment by BogdanCostinas** [comment] 2023-01-31 05:27
Describe the issue:
Trying to list a license for purchase and receiving an error "rejected by user"
Reproduce the behavior:
1)Login with Web Wallet (Maiar Connection) on my mobile phone
2)Go to Data NFT Wallet, list one license for 150 ITHEUM (150 entered manually in the box), proceed and sign in Maiar. 
3)Received "Rejected by user"

Expected behavior: I expected no errors during the transaction sign process

Device Used: Galaxy S21 5G 
Browser: Chrome 109.0.5414.118

There is also no withdraw button from the marketplace or change price

**Closed** 2023-01-31 05:41 UTC
Labels: bug

**Comment by fuzzyduke** [comment] 2023-02-01 10:25
Can we put in a mechanism so that the label doesn't distort the UI. 
If for "Listing price for each" the Input is large, then the label below gets temporarily misaligned.

![image](https://user-images.githubusercontent.com/121969933/216016839-1a9ff241-d5b2-4ef5-84b8-f2045d22c2c3.png)

**Comment by fuzzyduke** [comment] 2023-02-01 10:46
Suggestion: Provide a link to onchain explorer view of the Data NFT that will entail details of onchain interactions for that Data NFT, like transaction that show creation, burns, buys, sells, freeze, etc actions related to that Data NFT.

Could also consider embedding this view in a detail page for that Data NFT.

![image](https://user-images.githubusercontent.com/121969933/216021435-b4bf5d99-5108-4c0d-bc78-cf574dd02312.png)

**Comment by fuzzyduke** [comment] 2023-02-02 21:44
Suggestion:
Make available the royalty earned. This could be a history of royalties per Data NFT.

**Comment by newbreedofgeek** [comment] 2023-03-15 00:31
@fuzzyduke pls raise above items as seperate tickets (if you have not already.. so we can triage and track them seperate)
