### ISSUE TITLE
Implement Web Wallet signatures work for Data Marshal (like other wallets)

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#532] opened 2023-04-18 11:15 UTC
As @bucurdavid suggested.

```
By the way another workaround that came to my mind with the web wallet is using the SDK. But it’s not straightforward
Generating the marshal nonce
User copy the nonce, goes to web-wallet and sign
Come back and paste the nonce + signature
```

- In the Wallet page, once user clicks "View Data", we detect the wallet they used to log in. We can do this via a Context variable we have or direct via SDK if possible
- Now the progress model will have an extra workflow step, where we say that "Web Wallet" is not supported right now but a manual "signature verification step" can be used if needed
- Once Data Marshal gives you the nonce to sign in "pre access" step
- We ask the user to manually sign the nonce and enter it in a text box we present 
- We then continue as normal

**Comment by damienen** [comment] 2023-04-25 20:36
The login issue was solved.

But the signature was changed from string to buffer in the new version of sdk-core. I suggest we hold it off until after the BoY

**Comment by damienen** [comment] 2023-05-12 19:57
Apparently the issue is still present in the MultiversX sdk-dapp library...

I have notified them. I will leave this open, but until then I have activated the Web Wallet login button so it can be used for claims on mainnet.

**Comment by icegriffinguru** [comment] 2023-06-28 20:20
Implemented.
one issue is that data marshal api is called twice because props of LowerCard changes many times

**Comment by damienen** [comment] 2023-06-29 07:17
We need to prevent the file from loading twice (and modal loading twice)

**Comment by damienen** [comment] 2023-07-05 08:25
Works. Closing. Nice job, @icegriffinguru !

**Closed by damienen** 2023-07-05 08:25 UTC
Labels: enhancement
