### ISSUE TITLE
Skeleton loading boxes and actual NFT boxes are not aligned

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#390] opened 2023-03-21 10:46 UTC
If you look at the  "Recent Data NFTs" panel, the **skeleton loading boxes** and the **Data NFT Boxes** and perfectly aligned in X, Y position and width, height.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/743169/226582551-0c5ff4ad-f594-48f6-96b2-d38abe6c2792.png">

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/743169/226582646-0ee8a0d6-2aa7-4c1c-a61c-71a873afb188.png">

But have a look at this video, 
https://www.loom.com/share/dde3889032b747f5aae96688ed8bb2e6

In the Wallet and Marketplace views.. the skeleton loading boxes and NOT fully aligned (X, Y position and width, height).

Expected Behaviour:
- Wallet and Marketplace skeleton loading boxes vs Data NFT Boxes need to be perfectly aligned (X, Y position and width, height).
- The boxes need to be "evenly distributed" across the X axis. Consider changing it to use something like [chakra simple grid](https://chakra-ui.com/docs/components/simple-grid/usage). Have a look at the RecentDataNFT component

**Comment by damienen** [comment] 2023-03-23 20:42
The Skeleton loading boxes are still not aligned

**Comment by damienen** [comment] 2023-03-23 20:43
@Enciusan please watch Mark's video. It should help you understand more clearly what the issue is.

**Comment by damienen** [comment] 2023-03-27 18:33
Looks good! Closing

**Closed by damienen** 2023-03-27 18:33 UTC
Labels: bug
