### ISSUE TITLE
Web Wallet Login with JSON + (Web Wallet Maiar) - unable to send transactions (Rejected by user error)

### ISSUE THREAD

**Issue by damienen** [Itheum/data-dex#100] opened 2022-07-18 07:55 UTC
Seems that using dapp-core 1.3.2 adds some bugs for web wallet + json tx sending

**Comment by newbreedofgeek** [comment] 2022-11-30 23:31
After updating to dapp-core 2, this issue is still there so re-opening it.

**Comment by newbreedofgeek** [comment] 2022-11-30 23:33
Raised by community tester:

Rejected by user at Claim if I use Web Wallet, Maiar. I am using the phone now, Samsung S21 5G and Chrome.
Rejected by user also if I use the laptop with Chrome, web wallet connect, Maiar, for Send Me 10 ITH

![image](https://user-images.githubusercontent.com/743169/204930512-f645ea91-a197-4e6b-b960-205c30e99a8f.png)

**Comment by newbreedofgeek** [comment] 2022-12-13 00:31
Seems to be duplicate of https://github.com/Itheum/data-dex/issues/83

@damienen let's keep this open as a reminder that this bug is still an issue. But I will tag it as "external blocker"

**Closed** 2022-12-16 00:55 UTC
Labels: bug, blocked
