### ISSUE TITLE
Description: Newly Minted NFT doesn't show an image when listed in the Marketplace, however the Data NFT image is seen in the wallet.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#616] opened 2023-05-08 07:22 UTC
Newly Minted NFT doesn't show an image when listed in the Marketplace, however the Data NFT image is seen in the wallet.
https://devnet-explorer.multiversx.com/nfts/DATANFTFT4-3ba099-0171

Wallet
![image](https://user-images.githubusercontent.com/121969933/236760627-55d78161-c515-4e6e-9c76-86f27fdd2ce7.png)
Marketplace
![image](https://user-images.githubusercontent.com/121969933/236760707-1ead8853-3c0f-4cd8-b36f-4921c9d6d9cf.png)

**Comment by damienen** [comment] 2023-05-09 05:35
In wallet the full image is shown, but in marketplace thumbnail is shown so that's why it could be. @fuzzyduke what link did you use?

**Comment by damienen** [comment] 2023-05-11 20:55
Can't reproduce, closing

**Closed by damienen** 2023-05-11 20:55 UTC
