### ISSUE TITLE
Connecting with web wallet on stg.datadex seems to fail with redirection.

### ISSUE THREAD

**Issue by fuzzyduke** [Itheum/data-dex#1115] opened 2023-11-19 18:11 UTC
Connecting with web wallet on stg.datadex seems to fail with redirection.
Upon entering the password for the keystore we are redirected to the (https://wallet.multiversx.com/dashboard)

Expected behaviour is to be redirected back to the datadex having logged in with the keystore.

**Comment by damienen** [comment] 2023-11-20 09:28
Can't reproduce. Closing for now

**Closed by damienen** 2023-11-20 09:28 UTC
