### ISSUE TITLE
Explorer and Data DEX open side by side in same browser and using DeFi Wallet has issues

### ISSUE THREAD

**Issue by newbreedofgeek** [Itheum/data-dex#801] opened 2023-07-17 01:28 UTC
- Open Explorer in a tab
- Open Data DEX in a tab
- Login into Explorer via Defi Wallet and move around
- DON'T LOG OUT of Explorer, but in the Data DEX Tab.. login again via DeFi Wallet

issues:
- You will see the wallet popup appear a few times on Data DEX
- It logs in, but the menu indicates the user is not logged in nut the dashboard appears

Might be some session issue? as DeFi wallet is connected to 2 dApps in same browser.

**Comment by damienen** [comment] 2023-07-19 07:40
Can't reproduce it right now. It works all good to me.

Just the classic issue that sometimes I have to login two times, but that's prettu much it, @newbreedofgeek.

@fuzzyduke can you try to reproduce it, too? If you can, let me know, else, please close this issue as not planned

**Comment by fuzzyduke** [comment] 2023-07-19 11:46
Have run a few test cycles however not able to reproduce. Have experienced login issues in the past(required to log in 2-3 times) but not able to identify the exact sequence to reproduce. Closing as not planned as instructed.

**Closed by fuzzyduke** 2023-07-19 11:46 UTC
Labels: bug
